# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kolotoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulek', models.CharField(default='', max_length=127, verbose_name='Titulek')),
                ('obrazek', models.FileField(blank=True, max_length=255, null=True, upload_to='images/kolotoc', verbose_name='Obrázek')),
            ],
            options={
                'verbose_name': 'Kolotoč',
                'verbose_name_plural': 'Kolotoč',
            },
        ),
        migrations.CreateModel(
            name='Zpravy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True, verbose_name='Datum zveřejnění')),
                ('titulek', models.CharField(default='', max_length=127, verbose_name='Titulek')),
                ('obsah', models.CharField(default='', max_length=999, verbose_name='Obsah')),
                ('obrazek', models.FileField(blank=True, max_length=255, null=True, upload_to='images', verbose_name='Obrázek')),
                ('hlavni', models.BooleanField(default=False, help_text='Pokud je zaškrtnuto, zobrazí se mezi třemi hlavními články. Každý další hlavní článek může tento vystrčit ven a nebude tak již vidět.', verbose_name='Hlavní článek')),
            ],
            options={
                'verbose_name': 'Zpráva',
                'verbose_name_plural': 'Zprávy',
            },
        ),
        migrations.AddField(
            model_name='kolotoc',
            name='zprava',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashes.Zpravy'),
        ),
    ]
