# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kolotoc',
            name='obsah',
            field=models.CharField(default='', max_length=999, verbose_name='Obsah'),
        ),
    ]
